This is just a suggestion to migrate to standalone components etc
sibiraj-s/ngx-tiptap pull request #70
Opened 2024-07-02 20:47 UTC by Julian-B90

2024-07-19 05:41 UTC, sibiraj-s commented
Thanks, Will look into it. I would have preferred a discussion prior to making breaking changes.

2024-07-19 07:22 UTC, Julian-B90 commented
Maybe with that https://github.com/sibiraj-s/ngx-tiptap/pull/70/commits/2eb86c0a303c2fd42630eaff466fbe37bba937e3 we can offer both?

2024-07-19 12:08 UTC, sibiraj-s commented
> Maybe with that [2eb86c0](https://github.com/sibiraj-s/ngx-tiptap/commit/2eb86c0a303c2fd42630eaff466fbe37bba937e3) we can offer both?

I am not sure at this point if there would be any size increase if both are provided, since I never tried it.

Also, its fine to make breaking changes for a better API or make it more easy to use. I just said I wish there could have been a discussion nothing else.

2024-07-19 16:21 UTC, sibiraj-s requested changes
Thanks for the PR ❤️ 

Changes looks good to me, can you delete the module file? I will test these changes a bit and release them.

2024-07-19 16:21 UTC, sibiraj-s commented on projects/ngx-tiptap/src/lib/ngx-tiptap.module.ts
Can you delete this file, we can proceed with just standalone components, I can make a semver major release.

2024-07-19 16:21 UTC, sibiraj-s commented on projects/ngx-tiptap/src/public-api.ts
> +// export * from './lib/ngx-tiptap.module';
This line can be removed.

2024-09-25 10:13 UTC, sibiraj-s commented
Sorry for the delay, If you could resolve the conflicts, I can get it merged and released as next major.

2024-09-25 13:25 UTC, Julian-B90 commented
@sibiraj-s i have resolve the merge conflicts

2024-10-17 20:00 UTC, Julian-B90 commented
@sibiraj-s ?

2024-11-27 15:23 UTC, sibiraj-s approved these changes

2024-11-27 15:23 UTC, merged